spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: nayem
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          customerRequest:com.nayem.ecommerce.kafka.CustomerRequest,
          purchaseProductsRequest:com.nayem.ecommerce.kafka.PurchaseProductsRequest,
          orderConfirmation:com.nayem.ecommerce.kafka.OrderConfirmation
    consumer:
      bootstrap-servers: localhost:9092
      group-id: customerResponseGroup,purchaseProductsResponseGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: >
          customerResponse:com.nayem.ecommerce.kafka.CustomerResponse,
          purchaseProductsResponse:com.nayem.ecommerce.kafka.PurchaseProductsResponse

server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    payment-url: http://localhost:8222/api/v1/payments
    product-url: http://localhost:8222/api/v1/products